### PR TITLE
SetIsCategoryWithDecidableLifts/Colifts to true

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I will update `Toposes` after this PR is merged with failing CI.

**Comment by zickgraf** [comment]
Please retrigger the CI here once Toposes is updated.

**Comment by zickgraf** [comment]
@mohamed-barakat The CI is still failing: https://github.com/homalg-project/FinSetsForCAP/actions/runs/6954944289 Maybe Toposes has to be released first?

**Comment by mohamed-barakat** [comment]
Yes, you are right. Will trigger it after the release.

**Pull request merged**
