### PR TITLE
comply with CAP v2023.08-16

### PR DESCRIPTION
**Pull request by mohamed-barakat**
where PreComposeList now takes source and range as arguments

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
`FinSetsForCAP` produces worse compiled code without this adaptation, so bad that the CI times out.

**Comment by mohamed-barakat** [comment]
This is failing due to `FinSetsForCAP.jl`.

**Comment by zickgraf** [comment]
Codecov is having issues again. Since I do not see any reason why the coverage should drop, I will simply merge.

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Pull request merged**
