### PR TITLE
added missing mathematical properties: SetIsStrictC(oc)artesianCategory

### PR DESCRIPTION
**Pull request by mohamed-barakat**
which affects the derivation of the unitors and asccociators

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Please do not merge until https://github.com/homalg-project/CategoricalTowers/pull/493 is merged.

**Comment by mohamed-barakat** [comment]
I think it is failing because Julia does not properly handle the option `FinalizeCategory := true` passed to `TerminalCategoryWithSingleObject`.

**Comment by zickgraf** [comment]
Note: I have *not* done a mathematical review whether the implementation actually is strict.

**Comment by mohamed-barakat** [comment]
> Note: I have _not_ done a mathematical review whether the implementation actually is strict.

The implementation was always strict for coproducts but only became strict for products after I switched to the current convention for projections, this was quite some time ago.

**Pull request merged**
