### PR TITLE
AddAstrictionToCoimage

### PR DESCRIPTION
**Pull request by mohamed-barakat**
AddAstrictionToCoimage

ImageEmbedding( phi )      ⤳ Set
AstrictionToCoimage( phi ) ⤳ DuplicateFreeList

and compiled CoimageProjection

needs Toposes v2023.10-13

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
This PR will fail until https://github.com/homalg-project/CAP_project/pull/1495 is merged.

**Comment by mohamed-barakat** [comment]
@zickgraf: I think the last commit is what you had in mind :)

**Comment by zickgraf** [comment]
> @zickgraf: I think the last commit is what you had in mind :)

Yes, now we have the full analogy to the image and the code is much simpler :-)

Please add some tests for the newly added/compiled functions.

**Comment by mohamed-barakat** [comment]
> > @zickgraf: I think the last commit is what you had in mind :)
> 
> Yes, now we have the full analogy to the image and the code is much simpler :-)

Nice :)

> Please add some tests for the newly added/compiled functions.

I am preparing an example :)

**Pull request merged**
