### PR TITLE
AddCartesianCoevaluationMorphismWithGivenRange( SkeletalFinSets, ... )

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Review by zickgraf — CHANGES_REQUESTED** [review]
I suggest implementing `CartesianCoevaluationMorphism(WithGivenRange)` instead, then `CartesianLambdaIntroduction` can be derived. (Currently, only `CartesianEvaluationMorphismWithGivenSource`, i.e. only "one half" of the adjunction, is implemented). This has two advantages:

* It's much easier to check consistency (for checking the consistency of `CartesianLambdaIntroduction`, one basically has to derive it from `CartesianCoevaluationMorphism` anyway).
* 18 more derivations will be triggerd, e.g. `DirectProductToExponentialAdjunctionMap`.

**Comment by mohamed-barakat** [comment]
> I suggest implementing `CartesianCoevaluationMorphism(WithGivenRange)` instead, then `CartesianLambdaIntroduction` can be derived. (Currently, only `CartesianEvaluationMorphismWithGivenSource`, i.e. only "one half" of the adjunction, is implemented). This has two advantages:
> 
> * It's much easier to check consistency (for checking the consistency of `CartesianLambdaIntroduction`, one basically has to derive it from `CartesianCoevaluationMorphism` anyway).
> * 18 more derivations will be triggerd, e.g. `DirectProductToExponentialAdjunctionMap`.

Done. Together with Moussa Mbaye I implemented `AddCartesianCoevaluationMorphismWithGivenRange` and deleted `AddCartesianLambdaIntroduction`.

```gap
AddCartesianLambdaIntroduction( SkeletalFinSets,
  function ( cat, map )
    local S, T, images, a, b;

    S := Source( map );
    T := Range( map );

    images := AsList( map );

    a := Length( S );
    b := Length( T );

    return MapOfFinSets(
                   TerminalObject( cat ),
                   [ 1 + Sum( [ 1 .. a ], i -> ( images[i] - 1 ) * b^(a - i) ) ],
                   ExponentialOnObjects( cat, S, T ) );

end );
```

I hope we can recover something as efficient when we compile all CAP operations.

@TKuh: I believe the current error in the CI probably reveals a bug in `DirectProductExponentialCompatibilityMorphismWithGivenObjects` from `Toposes` stemming from `TensorProductInternalHomCompatibilityMorphismWithGivenObjects` from `MonoidalCategories`.

Now that more and more primitive operations are becoming purely functional, we should at some point consider changing the data structure of morphisms in `SkeletalFinSets` to functions instead of lists.

**Comment by mohamed-barakat** [comment]
This PR is building on PR #78.

**Comment by TKuh** [comment]
> I believe the current error in the CI probably reveals a bug in `DirectProductExponentialCompatibilityMorphismWithGivenObjects` from `Toposes` stemming from `TensorProductInternalHomCompatibilityMorphismWithGivenObjects` from `MonoidalCategories`.

I have looked into both derivations but I can't find any obvious mistakes. Can we investigate this on monday/tuesday?

**Comment by mohamed-barakat** [comment]
This updated PR now includes commit c108b799a8c36556c9f5b0fc0ffcf2c3db9573f4 which fixes a bug in `AddCartesianBraidingInverseWithGivenDirectProducts( SkeletalFinSets, ... )` introduced in commit 798c9fb3150d19ddc99745a9e0543ccd119269b8, a commit that had a misleading commit message

**Comment by zickgraf** [comment]
> This updated PR now includes commit [bb50335](https://github.com/homalg-project/FinSetsForCAP/commit/bb503351962ac318d88afc47034146da0b129146) which fixes a bug in `AddCartesianBraidingInverseWithGivenDirectProducts( SkeletalFinSets, ... )` introduced in commit [798c9fb](https://github.com/homalg-project/FinSetsForCAP/commit/798c9fb3150d19ddc99745a9e0543ccd119269b8), a commit that had a misleading commit message

Do you have an example which does not work with the old version? If yes, could you add it to the tests? Or is such an example already part of the tests in the last commit?

**Comment by mohamed-barakat** [comment]
Yes, the last commit includes an example. This is why the CI was broken.

**Comment by zickgraf** [comment]
Ah, I see! Then I will merge now.

**Pull request merged**
