### PR TITLE
fixed test-doc

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Please merge with failing CI.

**Comment by zickgraf** [comment]
Please make sure that this change is compatible with Julia, that is, also runs as part of FinSetsForCAP.jl.

**Comment by mohamed-barakat** [comment]
> Please make sure that this change is compatible with Julia, that is, also runs as part of FinSetsForCAP.jl.

The CI is failing with an error in Toposes.jl, even after merging https://github.com/homalg-project/CategoricalTowers/pull/478.

**Comment by mohamed-barakat** [comment]
We should discuss disabling testing of `FinSetsForCAP` in `CategoricalTowers`.

**Comment by mohamed-barakat** [comment]
Merged, as discussed with @zickgraf.

**Pull request merged**
