### PR TITLE
renamed Is(Skeletal)FiniteSet(Map) -> IsObject/MorphismIn(Skeletal)CategoryOfFiniteSets

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by zickgraf** [comment]
Some things:

1. The old names were much shorter and thus potentially better suited for didactical purposes. (I'm not against the change, I just wanted to mention it).
2. We should keep `FinSets` and `SkeletalFinSets` consistent, i.e. also rename `IsFiniteSet` and `IsFiniteSetMap`.
3. You can simply comment the synonyms for Julia, they should not be needed there.

**Comment by mohamed-barakat** [comment]
> Some things:
> 
> 1. The old names were much shorter and thus potentially better suited for didactical purposes. (I'm not against the change, I just wanted to mention it).

I don't like these names for two reasons:

* there is nothing called skeletal finite set. The word skeletal is referring to the category.
* I don't like the convention of having the suffix `Object/Morphism`, especially with the name of the category is too long. I prefer `IsObject/MorphismIn*`, where `*` can be an arbitrary long name.

> 2. We should keep `FinSets` and `SkeletalFinSets` consistent, i.e. also rename `IsFiniteSet` and `IsFiniteSetMap`.

Done.

> 3. You can simply comment the synonyms for Julia, they should not be needed there.

Done.

Thanks.

**Comment by zickgraf** [comment]
The GAP to Julia conversion now has support for `DeclareSynonym`: https://github.com/homalg-project/PackageJanitor/commit/d4fc09e2e670bf5928023760de87d55226da9b13 This was much easier then I expected, I thought GAP would handle synonyms in a much more elaborate way than just binding a global variable.

Also, as mentioned verbally, I suggest renaming `IsObjectInCategoryOfFinSets` to `IsObjectInFinSets` or `IsObjectInCategoryOfFiniteSets`, i.e. either use the shorthand `FinSets` or the full description `CategoryOfFiniteSets` (of course including similar renames for morphisms and SkeletalFinSets).

**Comment by mohamed-barakat** [comment]
> The GAP to Julia conversion now has support for `DeclareSynonym`: [homalg-project/PackageJanitor@d4fc09e](https://github.com/homalg-project/PackageJanitor/commit/d4fc09e2e670bf5928023760de87d55226da9b13) This was much easier then I expected, I thought GAP would handle synonyms in a much more elaborate way than just binding a global variable.

Nice. Still, the CI is failing.

> Also, as mentioned verbally, I suggest renaming `IsObjectInCategoryOfFinSets` to `IsObjectInFinSets` or `IsObjectInCategoryOfFiniteSets`, i.e. either use the shorthand `FinSets` or the full description `CategoryOfFiniteSets` (of course including similar renames for morphisms and SkeletalFinSets).

Done.

**Comment by zickgraf** [comment]
> > The GAP to Julia conversion now has support for `DeclareSynonym`: [homalg-project/PackageJanitor@d4fc09e](https://github.com/homalg-project/PackageJanitor/commit/d4fc09e2e670bf5928023760de87d55226da9b13) This was much easier then I expected, I thought GAP would handle synonyms in a much more elaborate way than just binding a global variable.
> 
> Nice. Still, the CI is failing.

You have to remove the comments for Julia again.

**Comment by mohamed-barakat** [comment]
The merge in CategoricalTowers is done. This can now be merged.

**Comment by zickgraf** [comment]
Please provide full backwards compatibility. As far as I can tell, the constructors are missing.

**Comment by mohamed-barakat** [comment]
> Please provide full backwards compatibility. As far as I can tell, the constructors are missing.

Done.

**Comment by mohamed-barakat** [comment]
I would suggest dropping the backward compatibility for `CategoryOfSkeletalFinSetsWithMorphismsGivenByListsPrecompiled` since it is not used outside of `FinSetsForCAP`.

**Comment by zickgraf** [comment]
> I would suggest dropping the backward compatibility for `CategoryOfSkeletalFinSetsWithMorphismsGivenByListsPrecompiled` since it is not used outside of `FinSetsForCAP`.

I agree, `CategoryOfSkeletalFinSetsWithMorphismsGivenByListsPrecompiled` is not a public interface.

**Comment by zickgraf** [comment]
Is there a reason why you have kept the constructor `CategoryOfFinSets` instead of renaming it to `CategoryOfFiniteSets`?

**Comment by mohamed-barakat** [comment]
> Is there a reason why you have kept the constructor `CategoryOfFinSets` instead of renaming it to `CategoryOfFiniteSets`?

This was an oversight. Done.

**Comment by mohamed-barakat** [comment]
> I agree, `CategoryOfSkeletalFinSetsWithMorphismsGivenByListsPrecompiled` is not a public interface.

Good.

**Pull request merged**
